export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('options').del()

  // Inserts seed entries
  await knex('options').insert([
    {
      id: 1,
      option: 'hydration port',
      description: 'option description',
      is_available: 1,
      is_custom: 0,
      is_color: 0,
      is_color_one: 0,
      is_color_two: 0,
      is_add_on: 1,
      price: 10,
    },
    {
      id: 2,
      option: 'map pocket',
      description: 'option description',
      is_available: 1,
      is_custom: 0,
      is_color: 0,
      is_color_one: 0,
      is_color_two: 0,
      is_add_on: 1,
      price: 50,
    },
    {
      id: 3,
      option: 'pink',
      description: 'main color/color option one',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 1,
      is_color_two: 0,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 4,
      option: 'yellow',
      description: 'main color/color option one',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 1,
      is_color_two: 0,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 5,
      option: 'orange',
      description: 'main color/color option one',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 1,
      is_color_two: 0,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 6,
      option: 'black',
      description: 'main color/color option one',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 1,
      is_color_two: 0,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 7,
      option: 'camo',
      description: 'main color/color option one',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 1,
      is_color_two: 0,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 8,
      option: 'custom color',
      description: 'main color/color option one',
      is_available: 1,
      is_custom: 1,
      is_color: 1,
      is_color_one: 1,
      is_color_two: 0,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 9,
      option: 'full custom',
      description: 'option description',
      is_available: 1,
      is_custom: 1,
      is_color: 0,
      is_color_one: 0,
      is_color_two: 0,
      is_add_on: 1,
      price: 0,
    },
    {
      id: 10,
      option: 'pink',
      description: 'accent color/color option two',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 0,
      is_color_two: 1,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 11,
      option: 'yellow',
      description: 'accent color/color option two',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 0,
      is_color_two: 1,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 12,
      option: 'orange',
      description: 'accent color/color option two',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 0,
      is_color_two: 1,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 13,
      option: 'black',
      description: 'accent color/color option two',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 0,
      is_color_two: 1,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 14,
      option: 'camo',
      description: 'accent color/color option two',
      is_available: 1,
      is_custom: 0,
      is_color: 1,
      is_color_one: 0,
      is_color_two: 1,
      is_add_on: 0,
      price: 0,
    },
    {
      id: 15,
      option: 'custom color',
      description: 'accent color/color option two',
      is_available: 1,
      is_custom: 1,
      is_color: 1,
      is_color_one: 0,
      is_color_two: 1,
      is_add_on: 0,
      price: 0,
    },
  ])
}
